- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-master-branch-jobs
      - openstack-python3-xena-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-functional
        - ipa-tox-examples
        # NOTE(iurygregory) Only run this two jobs since we are testing
        # wholedisk + partition on tempest
        - ipa-tempest-bios-ipmi-direct-src
        - ipa-tempest-uefi-redfish-vmedia-src:
            voting: false
        - ironic-standalone-ipa-src
        - metalsmith-integration-ipa-src
        - metalsmith-integration-ipa-src-uefi:
            voting: false
        # NOTE(dtantsur): non-voting because IPA source code is very unlikely
        # to break them. They rather serve as a canary for broken POST jobs.
        - ironic-python-agent-check-image-tinyipa:
            voting: false
        - ironic-python-agent-check-image-dib-centos8:
            voting: false
        # Non-voting jobs
        - ipa-tempest-ironic-inspector-src:
            voting: false
        - ipa-tox-bandit:
            voting: false
    gate:
      jobs:
        - openstack-tox-functional
        - ipa-tempest-bios-ipmi-direct-src
        - metalsmith-integration-ipa-src
        - ironic-standalone-ipa-src
    post:
      jobs:
        - ironic-python-agent-build-image-tinyipa
        - ironic-python-agent-build-image-dib-centos8
