- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - ipa-tempest-dsvm-partition-bios-ipmi-direct-tinyipa-src
        - ipa-tempest-dsvm-partition-bios-ipmi-iscsi-tinyipa-src
        - ipa-tempest-dsvm-wholedisk-bios-ipmi-direct-tinyipa-src
        - ipa-tempest-dsvm-wholedisk-bios-ipmi-iscsi-tinyipa-src
        # Non-voting jobs
        - ipa-tempest-dsvm-ironic-inspector-src:
            voting: false
        # NOTE(TheJulia): CoreOS jobs have a high failure rate.
        # In order to reduce the odds of things like nested virt
        # being detected but not available, we should treat them
        # as non-voting. This is in order to reduce the need to
        # recheck. If we non-voting tem on the gate, they are
        # pointless, and the odds seem to enable them to pass
        # more often than not.
        # https://storyboard.openstack.org/#!/story/2003985
        - ipa-tempest-dsvm-partition-bios-ipmi-direct-coreos-src:
            voting: false
        - ipa-tempest-dsvm-partition-bios-ipmi-iscsi-coreos-src:
            voting: false
        - ipa-tempest-dsvm-wholedisk-bios-ipmi-direct-coreos-src:
            voting: false
        - ipa-tempest-dsvm-wholedisk-bios-ipmi-iscsi-coreos-src:
            voting: false
        - openstack-tox-functional:
            voting: false
        - openstack-tox-lower-constraints
    gate:
      queue: ironic
      jobs:
        - ipa-tempest-dsvm-partition-bios-ipmi-direct-tinyipa-src
        - ipa-tempest-dsvm-partition-bios-ipmi-iscsi-tinyipa-src
        - ipa-tempest-dsvm-wholedisk-bios-ipmi-direct-tinyipa-src
        - ipa-tempest-dsvm-wholedisk-bios-ipmi-iscsi-tinyipa-src
        - openstack-tox-lower-constraints
    experimental:
      jobs:
        - ipa-tempest-dsvm-partition-bios-ipmi-iscsi-tinyipa256-src
        - ipa-tempest-dsvm-partition-ipmi-iscsi-tinyipa-python3
    post:
      jobs:
        - ironic-python-agent-buildimage-coreos
        - ironic-python-agent-buildimage-tinyipa

