- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-jobs
      - openstack-python3-jobs-arm64
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-functional
        - ipa-tox-bandit
        # NOTE(iurygregory) Only run this two jobs since we are testing
        # wholedisk + partition on tempest
        - ipa-tempest-bios-ipmi-direct-src
        - ipa-tempest-uefi-redfish-vmedia-src
        - metalsmith-integration-ipa-src-uefi
        # NOTE(rpittau): Currently broken because of an issue with parted
        - metalsmith-integration-ipa-src-legacy:
            voting: false
        - ironic-standalone-ipa-src
        # NOTE(dtantsur): non-voting because IPA source code is very unlikely
        # to break them. They rather serve as a canary for broken POST jobs.
        - ironic-python-agent-check-image-tinyipa:
            voting: false
        - ironic-python-agent-check-image-dib-centos9:
            voting: false
        # Non-voting jobs
        - ipa-tempest-ironic-inspector-src:
            voting: false
        - ipa-tox-codespell
    gate:
      jobs:
        - openstack-tox-functional
        - ipa-tox-bandit
        - ipa-tempest-bios-ipmi-direct-src
        - ipa-tempest-uefi-redfish-vmedia-src
        - metalsmith-integration-ipa-src-uefi
        # NOTE(rpittau): Currently broken because of an issue with parted
        #- metalsmith-integration-ipa-src-legacy
        - ironic-standalone-ipa-src
        - ipa-tox-codespell
    post:
      jobs:
        - ironic-python-agent-build-image-tinyipa
        - ironic-python-agent-build-image-dib-centos9
