name: Tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            libffi-dev \
            python3-dev \
            parted \
            gdisk \
            dosfstools \
            util-linux

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run unit tests
        run: tox -e py3

  pep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run pep8/linting
        run: tox -e pep8

  functional-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            libffi-dev \
            python3-dev \
            parted \
            gdisk \
            dosfstools \
            util-linux \
            qemu-utils

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run functional tests
        run: tox -e functional
